README.md
app/__init__.py
app/clam.py
app/main/views/scan.py
app/status/views.py
config.py

This should give us increased configurability. I don't know if we'll ever need to offer the TCP option (some people may find it hard to run a unix socket locally for some reason, i don't know), but that would at least be a feasible addition now.
At somepoint soon we should probably be getting some actual tests so our merges can be based on more than *shrug*s.

centralize acquiring clam socket through get_clamd_socket()

---

config.py

Without these the app will not grab the actual values from the env on startup.

config: set global empty defaults for `_TOKENS` config variables

---

app/callbacks/views/sns.py

I suspect SNS just uses `text/plain` for its requests.

sns: be more lenient with the content-type for sns requests

---

app/callbacks/views/sns.py
tests/callbacks/views/test_sns.py

sns: force request.get_json() to give us the json anyway even if the content-type is "text/plain"

---

app/callbacks/views/sns.py
tests/callbacks/views/test_sns.py

Turns out S3 through SNS *does* supply us a json dictionary as the payload of the `Message` key, it's just that it's a *json serialized* dictionary. JSON in JSON.
This copes with that and adds some tests around handling of it going wrong.

handle_s3_sns: expect "Message" to be a serialized json blob

---

app/callbacks/views/sns.py
config.py
tests/callbacks/views/test_sns.py

On the advice of @lfdebrux it would probably be useful for these `avStatus` result tags we're adding to be less opaque than json/base64 would make them. We might want to be able to make other tools act upon their values, and this is harder to do if those tools would first have to be able to decode our special blobs. For instance, it would stop us being able to e.g. set up permissions based on tag values.
With a view to fixing this, this PR, probably replacing https://github.com/alphagov/digitalmarketplace-antivirus-api/pull/12, separates the "metadata" out into separate tags. There is an added danger here that the message is lost among us that the `avStatus.*` key(s) are only ever supposed to be set *together* and never one on its own - always all referring to a single scanning event, …

 handle_s3_sns: tagging: set separate tags for avStatus instead of a single json blob

---

app/callbacks/views/sns.py
config.py
tests/callbacks/views/test_sns.py

Trello https://trello.com/c/RVmfbGgE/384-virus-scanning-functional-tests
This is to allow us to build functional tests with predictable outputs and run them without setting off false alarms. We do this by basing the notify "reference" on the bucket object's `ETag` (which in normal cases should be the file's md5) and by making sure alerts about such files are always "sent to" a specific dummy address.

handle_s3_sns: add special handling of case when only the eicar test file is found

---

.travis.yml
app/callbacks/views/sns.py
app/clam.py
app/decorators.py
app/main/views/scan.py
app/s3.py
config.py
tests/callbacks/views/test_sns.py
tests/conftest.py
tests/helpers.py
tests/main/test_views.py
tests/test_s3.py

https://trello.com/c/t0TuxSsb/387-non-sns-endpoint-to-process-a-file-for-virus-scanning
This is quite a basic endpoint intended mostly to be the target of a script yet to be written that will allow a bucket to be scanned "in bulk", either as a catch-up script or to add tags to a previously un-scanned bucket.
The endpoint is a POST request, accepting json containing the `bucketName`, `objectKey` and `objectVersionId` parameters. 
To support this, this PR includes quite a bit of refactoring, moving the "business" function to `app.s3` as `scan_and_tag_s3_object`. The return values (of both the function and view) should be enough to give a full picture of the findings of the scan and action the procedure took.
Another thing still to do is add this endpoint (and a whole new av-api client) to …

add endpoint for manually triggering scan

---

app/main/views/scan.py
tests/main/test_views.py

https://trello.com/c/ZSg7FK5s/201-apiclient-sort-out-timeouts-retrying-once-for-all
The thinking behind this is that because of the existing-tag-checking behaviour, this endpoint is in fact idempotent, and it's best to communicate this fact to middleware and client libraries so that e.g. they know retries are "safe".
Keeping `POST` backwards compatibility for now, but will probably eventually repurpose it as the "force rescan" variant.

scan_s3_object view: change this to a PUT request

---

app/main/views/scan.py
tests/main/test_views.py

https://trello.com/c/eI2PEVIY/202-create-jenkins-job-for-virus-scanning-catchup-script
These can happen when the antivirus-api doesn't have the required access to a specific object that a scan is requested for.

main.scan_s3_object endpoint: pass on 403 errors from s3 as 400s

---

app/status/views.py

...so that a pause, possibly caused by the "stats" call, doesn't cause a healthcheck to fail.
https://trello.com/c/a1HWW3Bd/550-antivirus-api-crashes
The output of this is now a _little_ ugly, having `"clamd"` and `"clamd.extended"` sections, but short of modifying the utils to be able to do deep merges, and seeing as this might not have any effect anyway, this is probably the most effective thing to do for now.
I note, looking at the "stats", that scraping these through prometheus might be an interesting experiment.

status checks: split "stats" out into separate, external, "clamd.extended" check

---

app/status/views.py

https://trello.com/c/a1HWW3Bd/550-antivirus-api-crashes
This is hopefully temporary so we can verify that these are what is causing the app "crashes".

status check: move all clamd checking to being an "external" dependency

---

Dockerfile

This had got left a bit behind.

Bump docker base image to 4.0.0

---

requirements-app.txt
requirements.txt

Trello: https://trello.com/c/rT3obXh5/543-check-whether-idna-dependency-in-antivirus-api-requirements-apptxt-can-be-unpinned
We could have revisited this card a lot sooner - the fix was put up a week after the card was created, and we pulled in the version of `requests` that included the fix (see https://github.com/requests/requests/commit/8761e9736f7d5508a5547cdf3adecbe0b7306278) late in December (https://github.com/alphagov/digitalmarketplace-antivirus-api/commit/a9768c78cc72df4ed7076cea042d0afe239276bf). 
Still, no harm done, and that's one less crouton in the dependency soup.

Remove pinned idna dependency

---

.pyup.yml

https://trello.com/c/mBmxDwfC/823-make-pyup-prs-appear-in-the-morning
Turns out we didn't have PyUp on Antivirus API yet. I've copied the config from the API app.

Adds PyUp config (weekly on Sundays)

---

Dockerfile
config/additional-supervisord.conf
default.nix

https://trello.com/c/0CgzmFeD
This PR includes both the base image bump which should improve the common daemons' shutdown but also the `clamd`-specific settings.
Also squeezed in a `default.nix` fix.

handle shutdown better

---

app/callbacks/views/sns.py
tests/callbacks/views/test_sns.py
tests/conftest.py
tests/main/test_views.py
tests/test_s3.py

https://trello.com/c/l2On3zPU
Turns out s3 key is url-quoted in SNS events. who knew?
> The s3 key provides information about the bucket and object involved in the event. The object key name value is URL encoded. For example, "red flower.jpg" becomes "red+flower.jpg" (Amazon S3 returns "application/x-www-form-urlencoded" as the content type in the response).
https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html
Also improve the tests to use a weirder key name.

handle_s3_sns: url-unquote s3 key sent to us in SNS events

---

Dockerfile

Ticket: https://trello.com/c/z7NZeoWF/1126-antivirus-api-failing-to-build

Update package libclamunrar7 to libclamunrar9

---

Dockerfile

https://trello.com/c/pXed0zB5/
requiring a change of `stretch` references to `buster`

docker base image: bump to 7.0.0

---

.flake8
.travis.yml
requirements-app.txt
requirements-dev.txt
requirements.txt

https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
- Bumps utils and test utils
- Enables Travis checks for Python 3.7 and 3.8
- Upgrades flake8 and removes `flake8-per-file-ignores` dependency

Enable Travis checks for Python 3.7 and 3.8

---

app/status/views.py
requirements-app.txt
requirements.txt

Update avapi to use new utils including signature change for `get_app_status`
Requires https://github.com/alphagov/digitalmarketplace-utils/pull/550
https://trello.com/c/B2GfZgfO/192-cause-additionalchecks-to-always-be-run-regardless-of-ignore-dependencies-on-status-endpoint

168-spike-check-a-newly-deployed-app-can-connect-to-its-paas-backing-service-timebox-1d

---

config/additional-supervisord.conf

clamav daemons run as a low privilege user and in doing this we should be removing their only means of accessing sensitive values provided to the app.
This notably includes the notify key. Tested on preview with smoulder tests & it works.
We could do similar things to our base image too, perhaps removing these envs from `nginx`/`awslogs` etc...

supervisord.conf: scrub potentially sensitive environment variables not needed by clam daemons

---

app/s3.py
config.py

https://trello.com/c/zH4wrBoU/1417-smoulder-tests-eicar-files-being-sent-to-2nd-line-email-rather-than-simulator
The Eicar test signature changed, so our smoulder tests started sending the alerts to the real 2nd line email address.
I've updated the code to allow a list of Eicar test strings (just in case the old signature re-appears as mysteriously as it left...)

Allow multiple Eicar test signatures

---

app/main/views/scan.py
requirements.txt
tests/callbacks/views/test_sns.py

https://trello.com/c/aQbWtees/1419-resolve-pyup-prs
The new version of Werkzeug introduces breaking changes for direct imports. We had been using `import werkzeug` to give us explicit namespacing to differentiate between `werkzeug.exceptions` and `requests.exceptions`, but given we've still got the latter, I think it's fine.
The tests now run 100% green with no warnings 😸

Update werkzeug imports

---

Dockerfile
config/additional-supervisord.conf

Stemming from https://trello.com/c/oGLgZAoJ
Didn't know we could do this before. See https://docs.python.org/3/library/configparser.html#supported-ini-file-structure
Also bumped docker base image to incorporate similar changes made to base `supervisord.conf`

supervisord.conf: use multiline strings for environment setting

---

Dockerfile
config/additional-supervisord.conf

Reverts alphagov/digitalmarketplace-antivirus-api#66 - I forgot to check the webserver still had permission to connecto to the `clamd` socket.

Revert "supervisord.conf: use multiline strings for environment setting"

---

Dockerfile
config/additional-supervisord.conf

Needed to switch the user we grant the `clamav` group membership to because the user we run the web server as changed.

Reinstate docker base 9.1.0 bump, with permissions fix in place

---

app/callbacks/views/sns.py
requirements.in
requirements.txt
tests/callbacks/views/test_sns.py

LXML is vulnerable to denial of service attacks when parsing untrusted documents.
Unfortunately, defusedxml lacks a couple of key features which we were using from LXML; namely good XPath support and the ability to get an element's namespace.
The only way of identifying an element's namespace in defusedxml is through the string representation of the element where it will appear as `"<Element '{http://an.example.namespace.com}ConfirmSubscriptionResponse' at 0x10e7fe4a8>"`
If there is a namespace, extract it from the string representation and insert it into the search string.
We can no longer get the contents of an element in the XPath, so we have to use a different XPath in `Element.find()`. This returns `None` if there's not a match, so wrap each search in a `try/except` block so we can …

Switch from LXML to defusedxml

---

Dockerfile

Ticket: https://trello.com/c/kTjetMY4/2181-docker-image-build-for-antivirus-api-will-stop-working-soon
The ClamAV team have decided to restrict downloading of antivirus definitions via Wget[[1]], so we use FreshClam instead.
I've tested this on my machine.
[1]: https://lists.clamav.net/pipermail/clamav-users/2021-March/010559.html

Use FreshClam to do initial download of virus definitions

---

Dockerfile

Because we no longer use wget to download virus definitions, we no longer need wget in our Docker image. This PR stops it from being installed. Thanks @idavidmcdonald for pointing this out.

Remove wget

---

Dockerfile

Pulls in alphagov/digitalmarketplace-docker-base#82 which fixes issues installing Python `cryptography` module.

Bump Docker base image

---

requirements-dev.txt
requirements.txt

The previous version of urllib3 has a known vulnerability. I don't think we're affected, but we should fix it anyway. Unfortunately, urllib3 is a transitive dependency of many other libraries. So to update urllib3, we also need to update the libraries that rely on it.

Update urllib3 and linked libraries
